Inprogress
tmhnsly/databaseProject pull request #4
Opened 2020-09-29 13:31 UTC by tmhnsly

2020-09-29 13:49 UTC, marcusxavier85 commented on functions.php
> +    return $result;
you can just put return before the $result = $query->fetchAll(); but this is easier to read.

2020-09-29 13:51 UTC, marcusxavier85 commented on functions.php
> +    $result = '';
this is confusing naming as you have the array "saved" into the $result var above

2020-09-29 13:53 UTC, marcusxavier85 commented on functions.php
> + *
doc blocking should follow the correct method.

/**
* Description of what it does
* @param name, data type and use
* @return type, description of what returning
*/

2020-09-29 13:54 UTC, marcusxavier85 commented on functions.php
> + *
Those dots are meant to be *

2020-09-29 14:01 UTC, marcusxavier85 commented on functions.php
> +        if (array_key_exists("name", $cards[0])) {
Line 27 isn't needed as you've already told the function that arrays only by putting that before the $cards var.

also with line 28 I don't think it's needed. It seems like extra code for the sake of extra code. Yeah you might not get a name but you're pulling from the database that will always have a name.

2020-09-29 14:15 UTC, tmhnsly commented on functions.php
> +        if (array_key_exists("name", $cards[0])) {
Fair points - works fine without them

2020-09-29 14:18 UTC, tmhnsly commented on functions.php
> +    $result = '';
My thought was Top Trumps cards, but i can totally see ho wthat doesn't make sense outside my head. Have changed $cards to $sithData.

2020-09-29 14:30 UTC, tmhnsly commented on functions.php
> +    $result = '';
fixed

2020-09-30 08:03 UTC, marcusxavier85 approved these changes

2020-10-01 09:11 UTC, JoshThomasField requested changes

2020-10-01 09:11 UTC, JoshThomasField commented on functions.php
> +function connectDB() :PDO {
You could change this function to accept a function name parameter, it would make it more reusable.
function connectDB($dbname) :PDO {
    $db = new PDO ('mysql:host=db; dbname='.$dbname, 'root', 'password');
    $db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    return $db;

2020-10-01 09:11 UTC, JoshThomasField commented on functions.php
> +function connectDB() :PDO {
Also have the semicolon attached to the brackets and a space then type hint. connectDB(): PDO {

2020-10-01 09:11 UTC, JoshThomasField commented on functions.php
> +function getSithData(PDO $db) :array {
Same here for the colon

2020-10-01 09:11 UTC, JoshThomasField commented on functions.php
> +function displaySithData(array $sithData) :string {
Same here for colon.

2020-10-01 09:12 UTC, JoshThomasField commented on functions.php
> +function connectDB() :PDO {
Write this one with the colon correction as well

2020-10-01 09:55 UTC, JoshThomasField approved these changes

2020-10-01 09:56 UTC, merged